# Underfloor heating pump controller integration Home Assistant
#
# This file adds two sliders for setting the threshold temperatures
# to switch the pump on and off.
# Automation's are added to synchronize the sliders with the values
# inside the controller. The controller stores these values in flash
# so it can run without Home Assistant.

input_number:
  # Slider for setting temperature to switch off the pump
  threshold_temp_off:
    name: Threshold Off
    unit_of_measurement: "°C"
    min: 0
    max: 50
    step: 1

  # Slider for setting temperature to switch on the pump
  threshold_temp_on:
    name: Threshold On
    unit_of_measurement: "°C"
    min: 0
    max: 50
    step: 1

# Synchronize controller and sliders
automation:
  - alias: sync threshold on with controller
    trigger:
      - entity_id: sensor.threshold_on
        platform: state
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.threshold_temp_on
        value: "{{ trigger.to_state.state | int }}"

  - alias: submit new 'on' value to controller
    trigger:
      - entity_id: input_number.threshold_temp_on
        platform: state
    action:
      service: esphome.pump_controller_threshold_on
      data_template:
        value: "{{ trigger.to_state.state | int }}"

  - alias: sync threshold off with controller
    trigger:
      - entity_id: sensor.threshold_off
        platform: state
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.threshold_temp_off
        value: "{{ trigger.to_state.state | int }}"

  - alias: submit new 'off' value to controller
    trigger:
      - entity_id: input_number.threshold_temp_off
        platform: state
    action:
      service: esphome.pump_controller_threshold_off
      data_template:
        value: "{{ trigger.to_state.state | int }}"

  - alias: FloorHeatingPump Anti Corrosion
    trigger:
      platform: time
      at: '01:30:00'
    condition:
      - condition: state
        entity_id: binary_sensor.floorheatingpump_pump_state
        state: 'off'
        for:
          hours: 24    
    action:
    #turn off automatic mode
    - service: switch.turn_off
      entity_id: switch.floorheatingpump_manual_automatic 
    # turn on the pump      
    - service: switch.turn_on
      entity_id: switch.floorheatingpump_on_off 
    # wait for 1 min      
    - delay: 
        minutes: 1
    # turn off the pump
    - service: switch.turn_off
      entity_id: switch.floorheatingpump_on_off
    # turn on automatic mode
    - service: switch.turn_on
      entity_id: switch.floorheatingpump_manual_automatic 
